server:
  port: 2635


#数据库
spring:
  datasource:
    url: jdbc:mysql:///dogcloud
    username: root
    password: 1001086
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名